#Load packages
library(ggplot2)
library(ggpubr)
library(CCA)
library(readxl)
library(vegan)
library(BiodiversityR)
library(ggplot2)
library(ggforce)
library(reshape2)
library(dplyr)
library(ggrepel)

#delete all the variables that are there in the environment
rm(list=ls()) 


############################################################################################################
############################################################################################################
#RDA CONTSRAINED ORDINATION FOR WOODY BIOMASS

##############################################################################################################
# NUMBA WOODY BIOMASS (700m)
########################################################################################
# load the data
numba_biomass_data <- read_excel("C:/Users/Kari Iamba/Desktop/Garden Final Data_2023/google drive_backup/For ANALYSIS/data/Numba_Biomass_2023.xlsx",
           sheet = "Numba_biomass_2023")


##############################################################################################################
#(A) Numba Woody plant data (700m)
numba_woody_species <-  numba_biomass_data  %>%
  filter(Plants %in% "woody") %>%
  group_by(Gardens, Treatments, Plant_sp) %>%
  summarise(Biomass = sum(Biomass_kg))  %>%
  arrange(desc(Biomass))

numba_woody_species3 <- numba_woody_species  %>% 
  reshape2::dcast(Gardens + Treatments ~ Plant_sp, value.var = "Biomass")

numba_woody_species3[is.na(numba_woody_species3)] <- 0 #removing NAs
numba_woody_species3

numba_woody_spp  <- numba_woody_species3[,3:117]#data frame/matrix of response (Y) variables

numba_woody_env  <- numba_woody_species3[,1:2] #data frame/matrix of explanatory (X) variables

#STATISTICS
species.Hellinger1 <- disttransform(numba_woody_spp, method='log')  #log transformation on woody biomass
Ordination.model1  <- rda(species.Hellinger1 ~ Treatments + Condition(Gardens), data= numba_woody_env, scaling=2)

set.seed(10)

#Partitioning of variance
Ordination.model1
summary(Ordination.model1)
#RDA1 explains 17.47% of the variation, RDA2 explains 5.29 %. 
#Blocks explained 32% while Treatments explained 16.68% of the variation in woody plant biomass. But 51.32% of the variation 
#is not explained by the treatments (explanatory variables) :[refer to Partitioning of variance]

vif.cca(Ordination.model1)
#no collinearity (no factors are inflating each other: they are all less than 20):rule of thumb


#What is the variance explained by the treatments?
RsquareAdj(Ordination.model1)$adj.r.squared #total variance explained by the RDA model
#The RDA’s adjusted R2 is 21.8%, and is significant (p = 0.001). 

#Is the model significant?
anova(Ordination.model1, perm = 999, adjust="tukey") #can also use: permutations = 999

#Which axes are significant?
anova(Ordination.model1, by = "axis", perm = 999, adjust="tukey") 

#Which terms are significant?
anova(Ordination.model1, by = "terms", perm = 999, adjust="tukey") 

#sequential test for contrasts
#anova.cca(Ordination.model1, by = "onedf", permutations = 999, adjust="tukey")
anova(Ordination.model1, by = "onedf", perm = 999, adjust="tukey")
#'arg' should be one of “terms”, “margin”, “axis”, “onedf”

#RDA PLOTTING 
#step 1
# script generated by the BiodiversityR GUI from the constrained ordination menu
species.Hellinger1 <- disttransform(numba_woody_spp, method='log')   #disttransform log transformation
Ordination.model1  <- rda(species.Hellinger1 ~ Treatments + Condition(Gardens), data= numba_woody_env, scaling=2)
#scaling="species" or scaling=1 shows similarities btw objects in response matrix. 
#Scaling=2 shows effect of Treatments or explanatory variable

summary(Ordination.model1)

plot1 <- ordiplot(Ordination.model1, choices=c(1,2))

#step 2
sites.long1 <- sites.long(plot1, env.data = numba_woody_env)
head(sites.long1)

species.long1 <- species.long(plot1)
species.long1

axis.long1 <- axis.long(Ordination.model1, choices=c(1, 2))
axis.long1

#step 3
spec.envfit1 <- envfit(plot1, env=species.Hellinger1)
spec.data.envfit1 <- data.frame(r=spec.envfit1$vectors$r, p=spec.envfit1$vectors$pvals)
species.long1 <- species.long(plot1, spec.data=spec.data.envfit1)
species.long1

#centroids
centroid1 <- sites.long1 %>%
  group_by(Treatments) %>%
  summarize(axis1=mean(axis1), axis2=mean(axis2))

sites.long1_axes <- sites.long1[,1:4]

#plot
numba_RDA_main_plot <- ggplot(sites.long1_axes, aes(x=axis1, y=axis2, color=Treatments)) +
  geom_point(size=2.5) +
  geom_point(data=centroid1, size=3, shape=22, fill= c("red", "darkgreen","grey","blue"), color="black") +
  geom_vline(xintercept = c(0), color = "grey50", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey50", linetype = 2) +
  geom_mark_ellipse(data=sites.long1, 
                    aes(x=axis1, y=axis2, 
                        color=Treatments, 
                        fill=after_scale(alpha(colour, 0.2))), # Use a transparent version of colour for fill
                    expand=0, show.legend=FALSE) +
  theme_test() + theme(plot.title=element_text(hjust=0.5)) + 
  labs(x="RDA1 [17.47%]") + labs (y="RDA2 [5.29%]") + ggtitle("") +
  theme(legend.title = element_text( size = 14),
        legend.text = element_text(size = 11)) +
  scale_color_manual(labels = c("C", "I","W","WI"), values = c("red", "darkgreen","grey","blue")) +
  theme(legend.position = c(0.13, 0.2),
        legend.direction = "vertical") + xlim(-2,2.5) + ylim(-2,2) +
  annotate(geom="text", x=c(-0.5,1.6,1,-0.6), y= c(1.2,0.2,-1.4,-0.4), label=c("C",'W',"WI","I"), size=7,
           color=c("red","grey","blue","darkgreen")); numba_RDA_main_plot

#Saving ordination plot
ggsave("numba_RDA_main_plot.jpg", width = 20, height = 18, units = "cm")


#Less then 90 degrees, they are positively correlated
#About 90 degrees, they are uncorrelated
#Greater then 90 degrees, they are negatively correlated


##############################################################################################################
# YAWAN WOODY BIOMASS (1700m)
########################################################################################
#load data for Yawan (1700m)
yawan_biomass_data  <- read_excel("C:/Users/Kari Iamba/Desktop/Garden Final Data_2023/google drive_backup/For ANALYSIS/data/Yawan_Biomass_2023.xlsx",
                                  sheet = "Yawan_biomass_2023")


#Yawan woody biomass 
yawan_Woody_species <-  yawan_biomass_data  %>%
  filter(Plants=="woody") %>%
  group_by(Gardens, Treatments, Plant_sp) %>%
  summarise(Biomass = sum(Biomass_kg)) %>% 
  arrange(desc(Biomass))

yawan_woody_species3 <- yawan_Woody_species %>% 
  reshape2::dcast(Gardens + Treatments ~ Plant_sp, value.var = "Biomass")

yawan_woody_species3[is.na(yawan_woody_species3)] <- 0 #removing NAs
yawan_woody_species3

yawan_woody_spp  <- yawan_woody_species3[,3:105] #species matrix
yawan_woody_env  <- yawan_woody_species3[,1:2] #explanatory matrix


#STATISTICS
species.Hellinger2 <- decostand(yawan_woody_spp, method='standardize')
Ordination.model2  <- rda(species.Hellinger2 ~ Treatments + Condition(Gardens), data= yawan_woody_env, scaling = 2)


set.seed(10)

#Partitioning of variance
Ordination.model2
#summary(Ordination.model2)

vif.cca(Ordination.model2)
#no collinearity (no factors are inflating each other: they are all less than 20):rule of thumb


#What is the variance explained by the treatments?
RsquareAdj(Ordination.model2)$adj.r.squared
#The RDA’s adjusted R2 is 35.29% 

#Is the model significant?
anova.cca(Ordination.model2, permutations = 999) #you can also use: permutations = 999

#Which axes are significant?
anova.cca(Ordination.model2, by = "axis",  permutations = 999) 

#Which terms are significant?
anova.cca(Ordination.model2, by = "terms", permutations= 999) 

#Which terms (treatments) are significant?
anova.cca(Ordination.model2, by = "onedf", permutations= 999, adjust="tukey")
#'arg' should be one of “terms”, “margin”, “axis”, “onedf”


#RDA PLOTTING for Yawan Woody Biomass
#step 1
# script generated by the BiodiversityR GUI from the constrained ordination menu
species.Hellinger2 <- disttransform(yawan_woody_spp, method='log')
Ordination.model2  <- rda(species.Hellinger2 ~ Treatments + Condition(Gardens), data= yawan_woody_env, scaling = 2)

summary(Ordination.model2)
#RDA1 explains 37.28% of the variation, RDA2 explains 5.43 %. 
#Blocks explained 26.77% while Treatments explained 32.33% of the variation in woody plant biomass. But 40.89% of the variation 
#is not explained by the treatments (explanatory variables) :[refer to Partitioning of variance]

plot2 <- ordiplot(Ordination.model2, choices=c(1,2))

#step 2
sites.long2 <- sites.long(plot2, env.data = yawan_woody_env)
head(sites.long2)

species.long2 <- species.long(plot2)
species.long2

axis.long2 <- axis.long(Ordination.model2, choices=c(1, 2))
axis.long2

#step 3
spec.envfit2 <- envfit(plot2, env=species.Hellinger2)
spec.data.envfit2 <- data.frame(r=spec.envfit2$vectors$r, p=spec.envfit2$vectors$pvals)
species.long2 <- species.long(plot2, spec.data = spec.data.envfit2)
species.long2


#plotting
#Adding ordispider diagrams
centroid2 <- sites.long2 %>%
  group_by(Treatments) %>%
  summarize(axis1=mean(axis1), axis2=mean(axis2))

sites.long2_axes <- sites.long2[,1:4]

yawan_RDA_main_plot  <- ggplot(sites.long2_axes, aes(x=axis1, y=axis2, color=Treatments)) +
  geom_point(size=2.5) +
  geom_point(data=centroid2, size=3, shape=22, fill= c("red", "grey","darkorange","blue"), color="black") +
  geom_vline(xintercept = c(0), color = "grey50", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey50", linetype = 2) +
  geom_mark_ellipse(data=sites.long2, 
                    aes(x=axis1, y=axis2, 
                        color=Treatments, 
                        fill=after_scale(alpha(colour, 0.2))), # Use a transparent version of colour for fill
                    expand=0, show.legend=FALSE) +
  theme_test() + theme(plot.title=element_text(hjust=0.5)) + 
  labs(x="RDA1 [37.28%]") + labs (y="RDA2 [5.43%]") + ggtitle("") +
  theme(legend.title = element_text( size = 14),
        legend.text = element_text(size = 11)) +
  scale_color_manual(labels = c("C", "I","W","WI"), values = c("red", "grey","darkorange","blue")) +
  theme(legend.position = c(0.13, 0.15),
        legend.direction = "vertical") + xlim(-1.6,1.65) + ylim(-2.5,2.5) +
  annotate(geom="text", x=c(-1.32,-0.5,0.5,0.9), y= c(-0.2,-0.8,1.35,-0.5), label=c("C","I","W","WI"), size=7,
           color=c("red", "grey","darkorange","blue")) ; yawan_RDA_main_plot

#Saving ordination plot
ggsave("yawan_RDA_main_plot.jpg", width = 20, height = 18, units = "cm")




#####---------------------------------------------------------
#combine ordination plots
#####---------------------------------------------------------
#combine ordination plots

library(grid)
library(cowplot)

combine_WP_RDA_main_plot <- cowplot::plot_grid(numba_RDA_main_plot,
                   yawan_RDA_main_plot, 
                   ncol = 2, byrow = TRUE,labels = c('A', 'B'), align="hv") ;combine_WP_RDA_main_plot

#Saving ordination plot
ggsave("combine_WP_RDA_main_plot.jpg", width = 30, height = 18, units = "cm")

